# Generated by Django 3.2.9 on 2021-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
