# Generated by Django 3.2.9 on 2021-12-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='URL'),
        ),
    ]
